version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/web/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/builder/"
    schedule:
      interval: "daily"
