version: "3.7"

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4-alpine3.9
    command: --maxmemory 200mb --maxmemory-policy allkeys-lru

  adminer:
    image: adminer:4.7.5
    ports:
      - 127.0.0.1:8080:8080

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      ENABLE_DEBUGPY: "1"
    ports:
      - 127.0.0.1:80:8000
      - 127.0.0.1:5678:5678
    healthcheck:
      disable: true
    depends_on:
      - db
      - redis
    volumes:
      - django-data:/app/var
      - ./django:/app
      - built-static:/app/static_built:ro

  builder:
    build:
      context: .
      dockerfile: ./docker/builder.Dockerfile
    volumes:
      - built-static:/app/build/
      - type: bind
        source: ./builder/gulpfile.js
        target: /app/gulpfile.js

volumes:
  db-data:
  django-data:
  built-static:
