version: "3.8"

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4-alpine3.9
    command: --maxmemory 200mb --maxmemory-policy allkeys-lru

  adminer:
    image: adminer:4.7.5
    ports:
      - 127.0.0.1:8080:8080

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:80:8000
    depends_on:
      - db
      - redis
    volumes:
      - web-data:/app/var
      - ./web:/app
      - built-static:/app/static_built:ro

  builder:
    build:
      context: .
      dockerfile: ./docker/builder.Dockerfile
    volumes:
      - built-static:/home/node/app/build
      - ./builder/src:/home/node/app/src:ro
      - ./builder/gulpfile.js:/home/node/app/gulpfile.js:ro

volumes:
  db-data:
  django-data:
  built-static:
