version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - built-static:/workspace/web/static_built:ro
      - .:/workspace
