name: Build & Test

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get node version
        id: node-version
        run: echo "::set-output name=node-version::$(node --version)"
      - uses: Gr1N/setup-poetry@v4
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Cache poetry venv
        id: cache-poetry
        uses: actions/cache@v2
        with:
          path: django/.venv
          key: "poetry-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('django/poetry.lock') }}"
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install poetry dependencies
        run: |
          cd django/
          poetry install
      - name: Cache pre-commit cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: "pre-commit-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ steps.node-version.outputs.node-version }}-\
            ${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: Run pre-commit
        run: |
          cd django/
          poetry run pre-commit run --show-diff-on-failure --color=always --all-files
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Get node version
        id: node-version
        run: echo "::set-output name=node-version::$(node --version)"
      - name: Cache npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "npm-${{ runner.os }}-\
            ${{ steps.node-version.outputs.node-version }}-\
            ${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            npm-${{ runner.os }}-${{ steps.node-version.outputs.node-version }}-
      - name: Install builder npm dependencies
        run: |
          cd builder/
          npm ci
      - name: Build builder
        run: |
          cd builder/
          npm run build
      - uses: Gr1N/setup-poetry@v4
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Cache poetry venv
        id: cache-poetry
        uses: actions/cache@v2
        with:
          path: django/.venv
          key: "poetry-${{ runner.os }}-\
            ${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('django/poetry.lock') }}"
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install poetry dependencies
        run: |
          cd django/
          poetry install
      - name: Copy built static files
        run: cp -r builder/build/ django/static_built/
      - name: Run collectstatic
        uses: ./.github/actions/run-django
        with:
          command: "python manage.py collectstatic --noinput"
      - name: Run pytest
        uses: ./.github/actions/run-django
        with:
          command: "pytest --no-cov"
      # - name: Run mypy
      #   uses: ./.github/actions/run-django
      #   with:
      #     command: "mypy ."
  build-docker:
    name: Build and test (Docker)
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t thunderstore:${GITHUB_SHA} .
      - name: Run pytest
        run: >
          docker run --rm
          --entrypoint pytest
          -e SECRET_KEY=hunter2
          -v "$(pwd)/coverage_results:/app/coverage_results"
          --no-healthcheck
          thunderstore:${GITHUB_SHA}
          --cov-report=xml:coverage_results/coverage.xml
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage_results/coverage.xml
      - name: Tag image
        run: |
          docker tag thunderstore:${GITHUB_SHA} riskofthunder/thunderstore:${GITHUB_SHA}
          docker tag thunderstore:${GITHUB_SHA} ghcr.io/risk-of-thunder/thunderstore:${GITHUB_SHA}
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push image to Docker Hub
        run: docker push riskofthunder/thunderstore
      - name: Login to GitHub Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.GHCR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GHCR_PAT }}
        run: docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/risk-of-thunder/thunderstore
